language: scala

addons:
  apt:
    packages:
      - openjdk-6-jdk

# Needed for openjdk6
sudo: required

jdk:
  - openjdk6
  - oraclejdk8
  - openjdk11

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-M5

env:
  global:
    # PGP_PASSPHRASE
    - secure: "BYC1kEnHjNrINrHYWPGEuTTJ2V340/0ByzqeihLecjoZ75yrjWdsh6MI1JEUWgv5kb+58vLzib21JfnjsPK6Yb2bSXuCFCsEtJNh6RJKgxkWlCOzfTSh5I2wl7PCjRClRL6gseX2uTSvFjL4Z//pmxwxeXlLp7voQe4QAUq1+sE="
    # SONA_USER
    - secure: "OpBwPc1GNvauageYOH3RscAa7wpZxgpmqDz15aigIKLNWzAhAtVUx0MleZ8rQeoqml6nrAvlnzuVHjKL2lVcjMPpjUis7bcQ5UAGK7tZK8x+qZNQxXmpXu8+pENwQA2yFaqt/xy7K5jFOrHJHTRxcPnyVG1yKakPWz53PPYUwbc="
    # SONA_PASS
    - secure: "Xw7rI/qlML1nD2e2XwlakkhKAWNGZKqqE+Q3ntTvFpfHryl7KLCvVzJ4LIavnL6kGJaWOgy9vlSoEWn5g9nqHSfE31C/k5pY5nTMAKiwiJzfAS+r0asKXW2gmKhwtcTBkqyLVOZLCJSPVlFRQyfBJHY+Fs0L3KWcnMQgtBlyDhU="
  matrix:
    # The empty SCALAJS_VERSION will only compile for the JVM
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.25
    - SCALAJS_VERSION=1.0.0-M6

matrix:
  exclude:
    - jdk: openjdk11
      env: SCALAJS_VERSION=0.6.25
    - jdk: openjdk11
      env: SCALAJS_VERSION=1.0.0-M6
    - scala: 2.11.12
      env: SCALAJS_VERSION=1.0.0-M6
    - scala: 2.11.12
      jdk: oraclejdk8
    - scala: 2.11.12
      jdk: openjdk11
    - scala: 2.12.8
      jdk: openjdk6
    - scala: 2.13.0-M5
      jdk: openjdk6

script: 
  # work around https://github.com/travis-ci/travis-ci/issues/9713
  - if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi
  - java -version
  - admin/build.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
